server:
  port: 8080
person:
  address: 大连街老酒馆
##指定生效的环境
#spring:
#  profiles:
#    active: prod


##指定日志级别
logging:
  level:
    com.zpy: error




---
server:
  port: 8081
spring:
  profiles: dev


---

server:
  port: 8082
spring:
  profiles: prod